describe('Genome offline fixture', () => {
  beforeEach(() => {
    cy.stubGenomeFromFixture('GCF_000195955.2')
    cy.visit('/')
  })

  it('shows annotations for the fixture genome on Genome Summary', () => {
    cy.seedDownloadedGenome('GCF_000195955.2')
    cy.get('[data-cy="genome-summary-tab-label"]').click()
    cy.wait('@loadedGenomes')
    cy.get('[data-cy="genome-selector-pane"]').find('select').select('GCF_000195955.2')
    cy.wait('@annotations')
    cy.contains('dnaA').should('be.visible')
    cy.contains('Total genes in DB:').should('be.visible')
  })

  it('shows only the fixture genome in the available catalog', () => {
    cy.get('[data-cy="genome-management-tab"]').click()
    cy.wait('@catalogGenomes')
    cy.contains('Mycobacterium tuberculosis H37Rv').should('be.visible')
    cy.contains('GCF_000195955.2').should('be.visible')
    cy.contains('Available prokaryotic genomes')
      .parent()
      .find('input[type="checkbox"]')
      .should('have.length', 1)
  })

  it('deletes the fixture genome from the downloaded list on Genome Management', () => {
    cy.get('[data-cy="genome-management-tab"]').click()
    cy.wait('@catalogGenomes')
    cy.contains('Available prokaryotic genomes')
      .parent()
      .find('input[type="checkbox"]')
      .first()
      .check()
    cy.contains('button', 'Download').click()
    cy.wait('@loadGenome')
    cy.wait('@loadedGenomes')
    cy.get('[data-cy="genome-catalog-item"]').first().find('input[type="checkbox"]').check()
    cy.get('[data-cy="select-all-delete-button"]').click()
    cy.get('[data-cy="delete-genomes-button"]').should('be.enabled').click()
    cy.wait('@deleteGenomes')
    cy.contains('GCF_000195955.2: Not found').should('not.exist')
    cy.contains('No genomes downloaded yet.').should('be.visible')
  })

  it('shows the correct number of annotations for the fixture genome', () => {
  cy.stubGenomeFromFixture('GCF_000195955.2')
  cy.visit('/')
  cy.seedDownloadedGenome('GCF_000195955.2')
  cy.get('[data-cy="genome-summary-tab-label"]').click()
  cy.get('select').select('GCF_000195955.2')
  cy.wait('@annotations')
  cy.contains('dnaA').should('be.visible')
  cy.contains('Total genes in DB:').should('be.visible')
  })
})